export const track = [
  {
    id: 1,
    cover: 'cover',
    title: 'title',
    description: 'description',
    audio: 'audio',
    isActive: true,
  },
  {
    id: 1,
    cover: 'cover',
    title: 'title',
    description: 'description',
    audio: 'audio',
    isActive: true,
  },
  {
    id: 1,
    cover: 'cover',
    title: 'title',
    description: 'description',
    audio: 'audio',
    isActive: true,
  },
  {
    id: 1,
    cover: 'cover',
    title: 'title',
    description: 'description',
    audio: 'audio',
    isActive: true,
  },
  {
    id: 1,
    cover: 'cover',
    title: 'title',
    description: 'description',
    audio: 'audio',
    isActive: true,
  },
  {
    id: 1,
    cover: 'cover',
    title: 'title',
    description: 'description',
    audio: 'audio',
    isActive: true,
  },
  {
    id: 1,
    cover: 'cover',
    title: 'title',
    description: 'description',
    audio: 'audio',
    isActive: true,
  },
  {
    id: 1,
    cover: 'cover',
    title: 'title',
    description: 'description',
    audio: 'audio',
    isActive: true,
  },
  {
    id: 1,
    cover: 'cover',
    title: 'title',
    description: 'description',
    audio: 'audio',
    isActive: true,
  },
  {
    id: 1,
    cover: 'cover',
    title: 'title',
    description: 'description',
    audio: 'audio',
    isActive: true,
  },
  {
    id: 1,
    cover: 'cover',
    title: 'title',
    description: 'description',
    audio: 'audio',
    isActive: true,
  },
  {
    id: 1,
    cover: 'cover',
    title: 'title',
    description: 'description',
    audio: 'audio',
    isActive: true,
  },
  {
    id: 1,
    cover: 'cover',
    title: 'title',
    description: 'description',
    audio: 'audio',
    isActive: true,
  },
  {
    id: 1,
    cover: 'cover',
    title: 'title',
    description: 'description',
    audio: 'audio',
    isActive: true,
  },
  {
    id: 1,
    cover: 'cover',
    title: 'title',
    description: 'description',
    audio: 'audio',
    isActive: true,
  },
  {
    id: 1,
    cover: 'cover',
    title: 'title',
    description: 'description',
    audio: 'audio',
    isActive: true,
  },
  {
    id: 1,
    cover: 'cover',
    title: 'title',
    description: 'description',
    audio: 'audio',
    isActive: true,
  },
  {
    id: 1,
    cover: 'cover',
    title: 'title',
    description: 'description',
    audio: 'audio',
    isActive: true,
  },
];

export const many = [...track, ...track, ...track, ...track, ...track];
export const tracks = [];
many.forEach((el, idx) => {
  const obj = {};
  Object.keys(el).forEach((key) => { obj[key] = idx + (el[key]); });
  tracks.push(obj);
});
